# Generated by Django 5.0.2 on 2024-02-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=110)),
                ('date', models.DateTimeField(verbose_name='%Y-%m-%d %H:%M:%S')),
                ('location', models.URLField()),
                ('description', models.TextField()),
                ('image', models.URLField(blank=True, null=True)),
                ('about', models.TextField()),
                ('assistants_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
